FROM python:3-slim AS build-env
# Set working directory in the image
WORKDIR /app

# Copy files from host filesystem to image file system
COPY . /app

# Install the necessary packages
RUN apt-get update && apt-get install -y python3 python3-pip

FROM gcr.io/distroless/python3

COPY --from=build-env /app /app

WORKDIR /app

# Run command to start the application
CMD ["python3", "app.py"]



